### ISSUE TITLE
Version 0.7.10  hide all my group y channel.

### ISSUE THREAD

**Issue by carlosgonz0** [elros34/depecher#15]
I can not use it Depecher 0.7.10.
After install look like this:
![Captura_20201106_002](https://user-images.githubusercontent.com/45316884/98420834-077f6d80-2056-11eb-900d-d80669b24485.png)

**Comment by carlosgonz0** [comment]
All the group y channel they disappear when I use the pulley option: Reset dialog

**Comment by elros34** [comment]
Thanks, indeed I broke "Reset dialogs".

**Comment by carlosgonz0** [comment]
It is fixed now.
Thx u.
