### ISSUE TITLE
Line: 818 from es.ts file not get translations

### ISSUE THREAD

**Issue by carlosgonz0** [elros34/depecher#17]
Line: 818 issues to get translation.

**Comment by elros34** [comment]
Please tell where in ui it is not tranlsated and in what situtions instead some line number.

**Comment by elros34** [comment]
From what I can see whole share ui is not translated and not updated (undefined strings) so certainly not only line 818

**Comment by carlosgonz0** [comment]
You right it is not only line 818, is the whole page. Good catch elros.

**Comment by carlosgonz0** [comment]
other issue in the same share-page is with the icon, i created one to fix is there in #11
