### ISSUE TITLE
FR: aarch64

### ISSUE THREAD

**Issue by carlosgonz0** [elros34/depecher#19]

**Comment by elros34** [comment]
Do you want to use depecher on aarch64 or this request is purely for fun or other reasons? I ask because I don not want to spend time on building tdlib and depecher if nobody really need it and I can't test on my armv7hl sfos port. Also looks like aarch64 apps tend to crash on sfos 4 when used together with silica booster.

**Comment by carlosgonz0** [comment]
Well i am still using Depecher  on Xperia X, then i moved to Sony xperia 10 II, also many Telegram-spanish-sailfish user  is ask me for depecher aarch64.
I  am happy to test Depecher aarch64 when you release the .rpm package.

**Comment by elros34** [comment]
OK then I will see what I can do.

**Comment by elros34** [comment]
Here you go arm64 version [edit new release version]: https://github.com/elros34/depecher/releases/tag/0.8.0
Use together with updated tdlib: https://github.com/elros34/td/releases/tag/1.5.0-1

**Comment by carlosgonz0** [comment]
Thank you @elros34, I thankful with  you.

**Comment by elros34** [comment]
Maybe I wasn't clear enough, this is test/debug version not suitable for daily usage, it will produce a lot of logs if it works at all.

**Comment by carlosgonz0** [comment]
Well i installed it worked good, do you need the log?

**Comment by elros34** [comment]
Only if it crash or something is not working compared to previous release. I had to make some changes to registration (for new phone number) after updating tdlib so that is not tested. If there is no regression then I will upload new release within few days.

**Comment by carlosgonz0** [comment]
OK.  I'll tell you here, if I find a problem in Depecher aarch64.
