### ISSUE TITLE
FR: Option to filter chats/groups 

### ISSUE THREAD

**Issue by carlosgonz0** [elros34/depecher#20]

**Comment by carlosgonz0** [comment]
Search Chats  is another feature  clamed to many user on Spanish-Sailfish-Telegram.

**Comment by elros34** [comment]
What exactly do you mean by 'Search Chats'?

**Comment by carlosgonz0** [comment]
Just If a have many  groups  already in my Depecher then  i want a option to seach which group i want to go.

**Comment by carlosgonz0** [comment]
Like: Filter groups.
