### ISSUE TITLE
FeatureRequest: clicked user from group details to user page

### ISSUE THREAD

**Issue by carlosgonz0** [elros34/depecher#24]
This feature will useful to send a message to a user from a group.
![Captura_20210927_004](https://user-images.githubusercontent.com/45316884/134966561-a55aec9f-7dc0-4451-b4c7-432d9a93a881.png)

**Comment by elros34** [comment]
Added in 0.8.1 but something still might be broken.

**Comment by carlosgonz0** [comment]
Ok the broken is that if i use this feature, then i go back at HOME i can not go at same group because  seems blocked, to fix this i need to go back at HOME to go to another group then go back  at same group which i used this feature and now seems unblocked.

**Comment by elros34** [comment]
Anything special about group on which you have tried it or user you want to talk? I can not reproduce it when Opening chat to myself or Pollbot. I have tried in super groups, I guess it happens on different kind of groups?

**Comment by carlosgonz0** [comment]
@elros34 to reproduce the bug you need pull down the menu to send a message from the user page of the group list.

**Comment by carlosgonz0** [comment]
@elros34  this bug already fixed on the last commits?

**Comment by elros34** [comment]
I hope so but needs to be confirmed

**Comment by carlosgonz0** [comment]
Give me a release i check it. :D

**Comment by carlosgonz0** [comment]
> @elros34 to reproduce the bug you need pull down the menu to send a message from the user page of the group list.

This bug i talk about it.

**Comment by elros34** [comment]
done

**Comment by carlosgonz0** [comment]
Until now I was able to install the new version of Depecher, so WOW it work really nice i am happy with this amazing release. Thank @elros34 you  are the best definitely !
Yes this bug it fully fixed.
