### ISSUE TITLE
Remove the bool-funtion at home. 

### ISSUE THREAD

**Issue by carlosgonz0** [elros34/depecher#27]
This a very old bug, when i go at any group then go back, the bool funtion stayed enabled. So when i go at home it not need bools-funtion enabled, so when i go back at home. There should be not any function when sliding to the left because i am at home.

**Comment by elros34** [comment]
It's not a bug it's a feature. Even more sailfishos specific feature: attached Page. Indicator shows that particular chat is opened and you can quickly activate it using swipe.

**Comment by carlosgonz0** [comment]
Yes i know that sailfish feature, but when we are on HOME on depecher this feature need be removed for better understanding...
If we are on the page group this feature is OK, but on Home I not seen useful, even looking a bug.

**Comment by elros34** [comment]
I do not see any reason to remove it. It allows quick access to chat without slow loading of messages.

**Comment by carlosgonz0** [comment]
May be i wrong, but this feature on Home it looking a bug than a feature.

**Comment by carlosgonz0** [comment]
You are right when you say it prevent the slow loading, but the big problem is that if i am at Home i do not know which channel or contact is enabled to swipe to the left.

**Comment by elros34** [comment]
So maybe adding some kind of highlight for currently opened chat is good idea.

**Comment by carlosgonz0** [comment]
Yes adding a highlight it good feature. :  )

**Comment by carlosgonz0** [comment]
> So maybe adding some kind of highlight for currently opened chat is good idea.

There  is  a issue yet here, so when i use it the #24 funtions then i go back to Home there is no more  highlight for opened chat.

**Comment by elros34** [comment]
Can't reproduce

**Comment by carlosgonz0** [comment]
Ok i will debugging more.

**Comment by carlosgonz0** [comment]
> Can't reproduce

Try on basic group please. I reproducing this bug here on xperia x, xperia seine

**Comment by carlosgonz0** [comment]
> Can't reproduce

Mmm i rechecked and may be it is not a real bug. I closing...

**Comment by carlosgonz0** [comment]
I will  send a new Pull Request to fix the icon share.
