### ISSUE TITLE
Sticker animated in 8.1

### ISSUE THREAD

**Issue by carlosgonz0** [elros34/depecher#28]
There is  a possibility to increase the size of  the static sticker animated? currently is looking too tiny.

**Comment by elros34** [comment]
I do not use them usually so please be more specific of what kind of sticker. Animated stickers are not supported, only thumbnails are shown. Did it change at some point? I remember changing something to match my display.

**Comment by carlosgonz0** [comment]
Well on Depecher v8.1 i can now send/save/look/detete sticker animated(.tgs files) as well, but this tgs files can not be played on motion on Depecher because it need a rlotie module, but currently this tgs files can be showed like a thumbnails image without motion, so this thumbnails is looking too tiny on my sony xperia 10 II , so it coud be better if this thumbnails get better sizes, like big or medium thumbnails if possible to implement.

**Comment by carlosgonz0** [comment]
https://github.com/Samsung/rlottie

**Comment by carlosgonz0** [comment]
So i think that under tdlib1.5 animated sticker can be developed by using the lib rlottie.   Because currently Depecher  v.8.1 can manager .TGS files already.
https://github.com/tdlib/td/blob/master/CHANGELOG.md

**Comment by elros34** [comment]
Tdlib supports it but there is no tgs support it depecher, these are regular images. I have added thumbnails to avoid empty messages but I do not have plans to support animated stickers. I am afraid thumbnails for animated stickers have reduced size but need to confirm it.

**Comment by elros34** [comment]
OK I got from tdlib thumbnails with 128 pixels height so probably it wont be fixed unless I scale them up which will looks little ugly.

**Comment by carlosgonz0** [comment]
> Tdlib supports it but there is no tgs support it depecher, these are regular images. I have added thumbnails to avoid empty messages but I do not have plans to support animated stickers. I am afraid thumbnails for animated stickers have reduced size but need to confirm it.

 Yesterday i was able to add/save .tgs files under Depecher, then i was able to send a .tgs file as well, this tgs on motion  was played well on   Yottagram or oficial Telegram client.

**Comment by carlosgonz0** [comment]
I know that Depecher is not have complete TGS support, because this not have animation, but currently can manager tgs files as well for sure. Before at version 8.1 this tgs manager was not possible.
