### ISSUE TITLE
FeatureRequest: Gif support on profile  details 

### ISSUE THREAD

**Issue by carlosgonz0** [elros34/depecher#32]
All others features it already supported  on Depecher, just missing GIF and Voice-Massage on group/user profile details section.

**Comment by carlosgonz0** [comment]
It will cool if Depecher it has GIF manager. Some peoples shares nice GIF then i do not have a way to save/send that GIF, or saves all gif shared on a Telegram group.

**Comment by elros34** [comment]
Not sure about manager but gifs in details page should be possible. Do you have some channel with gifs for testing? I have checked few which claim to have gifs but in reality they use mp4 files.

**Comment by carlosgonz0** [comment]
I checked some Telegram GIFs and yes it is gif,mp4.
GIF Manager mean an option to save and send  gif.mp4 like the smile icon to send animated-sticker/sticker.
As the GIF is a MP4 we can add a option on choose Type too: 

![Gif-Depecher](https://user-images.githubusercontent.com/45316884/141531673-c4d30be0-e910-4452-8ddb-51378e321cc9.png)

**Comment by carlosgonz0** [comment]
But this option to send GIF it need a static or dinamic preview to know which gif we are sending...
On profile it cool do add the option to GIT to catch all git sent from a group or user and of course a option to download to the folder that depecher already it goint to use to preview and send...

**Comment by carlosgonz0** [comment]
Or we can use it the way for the sticker icon to send gif on somewhere there a section.

**Comment by carlosgonz0** [comment]
On Depecher 0.8.3 i can not see the way to send GIF? It is implemented?

**Comment by elros34** [comment]
No, there is no any special menu for videos or fake gifs (which are videos anyway) except general way to send any files.

**Comment by elros34** [comment]
No, there is no any special menu for videos or fake gifs (which are videos anyway) except general way to send any files.

**Comment by elros34** [comment]
No, there is no any special menu for videos or fake gifs (which are videos anyway) except general way to send any files.

**Comment by elros34** [comment]
No, there is no any special menu for videos or fake gifs (which are videos anyway) except general way to send any files.

**Comment by carlosgonz0** [comment]
> No, there is no any special menu for videos or fake gifs (which are videos anyway) except general way to send any files.

OK

**Comment by carlosgonz0** [comment]
You did an excellent work. THX.

**Comment by carlosgonz0** [comment]
> No, there is no any special menu for videos or fake gifs (which are videos anyway) except general way to send any files.

You did an excellent work. THX.
