### ISSUE TITLE
More space between Group or User.

### ISSUE THREAD

**Issue by carlosgonz0** [elros34/depecher#36]
Some peoples on Spanish Telegram group  it complaint that User and Group it very close to each other, so little space between each other should fine.

![complay](https://user-images.githubusercontent.com/45316884/140818033-1ef8fdcd-4154-471a-8cef-944d14b6f20c.png)

**Comment by elros34** [comment]
I am not convinced. Seems fine for me especially in landscape mode where space is limited.
BTW screenshot is confusing

**Comment by carlosgonz0** [comment]
Yeah the screenshot it confusing, i just quickly reused the screenshot for one example.

I think too that the Element(the circles with the avatars)   are to close one to next one, just separate a little more should be fine.
