### ISSUE TITLE
FeatureRequest: button to use a Tele-wallpaper

### ISSUE THREAD

**Issue by carlosgonz0** [elros34/depecher#4]
The background wallpaper is here:
![telegrambackground](https://user-images.githubusercontent.com/45316884/97109669-e5c3d500-16aa-11eb-8ea3-9bb134c76a62.png)

**Comment by carlosgonz0** [comment]
The Wallpaper feature request is stopped for the moment due to resolve licences.

**Comment by carlosgonz0** [comment]
Hi @elros34 the commit d93d57f3b29520762d178310e68a922b766acd32 seems fixed lot bugs in Depecher. Good work!
Also i would like if you can push this nice wallpaper into the Apps. Sailfish_es Telegram group they like a lot depecher.
I do not found the license for this, but i believe that the license is free to use it. I will searching...

**Comment by elros34** [comment]
I saw some references to background in tdlib so probably that is a proper way to handle it. Frankly I don't see it as a useful feature on sfos when every apps have already some system wallpaper with pattern.

**Comment by carlosgonz0** [comment]
Yes it is a small feature. But looks nice in SF  and increase the Telegram experience.  Oficial Telegram client has this features to choose several wallpaper in Telegram app background.

**Comment by carlosgonz0** [comment]
Other feature will be nice in Depecher is, shown how many people is conected, currently only shown how many members. 
Telegram has a lot funny features, but I do not want to push it at you to work :  ), I thankfull for all...

**Comment by elros34** [comment]
Yes many things are missing but unlikely I will implement them. Current state is fine for me except lack of calls which seems too complicated for me so don't put your hopes for new features too high.

**Comment by carlosgonz0** [comment]
I think that Depecher will look beautiful with this wallpaper on background. :  )
