### ISSUE TITLE
DepacherSettingPage not get translation.

### ISSUE THREAD

**Issue by carlosgonz0** [elros34/depecher#5]
I already full translated depecher settings page, but is not working.
![Captura_20201024_001](https://user-images.githubusercontent.com/45316884/97109823-d6915700-16ab-11eb-93ee-1ab975b45a23.png)

**Comment by elros34** [comment]
Yes I did notice it but I didn't investigate it so far. I guess translations for jolla-settings needs to be in declared somewhere or placed in correct place.

**Comment by carlosgonz0** [comment]
Thank you. I am working in fixing the depecher-icon-plugin too desing.
