### ISSUE TITLE
FeatureRequest: Add delete conversations

### ISSUE THREAD

**Issue by carlosgonz0** [elros34/depecher#7]
Add: delete conversations.
Remove: leave chat, mute/unmute, then move it to infoPage already implemented. Reduce twice the same options.
![RePAINT01025_001_edit_edit_edit_edit](https://user-images.githubusercontent.com/45316884/97111401-d9dd1080-16b4-11eb-967e-38efe35b06a8.png)

**Comment by carlosgonz0** [comment]
I am not sure how hard implement, but this funtion is a lot needed to keep clean the depecher interface. Like delete unwanted conversations.

**Comment by carlosgonz0** [comment]
This feature was implement finally on 0.8.2.

**Comment by carlosgonz0** [comment]
It only delete conversations for groups but not for individual contact user.

**Comment by elros34** [comment]
hmm should be exactly the opposite. I have only added "Remove history and leave chat" for private chats

**Comment by carlosgonz0** [comment]
Mmm I wrong i did a quick test now and  look like that delete for User chat("Remove history and leave chat") work, but not for groups.. private chats too work. So can you add  "Remove history and leave chat" for regular groups chats? it easy to add it?

**Comment by carlosgonz0** [comment]
Thank you.
